### PR TITLE
Upgraded selenium-server jar to version 2.0rc2 in order to support Firefox 4

### PR DESCRIPTION
**Pull request by luccastera**
The selenium jar that was shipping with Lebowski did not work on Firefox 4. After updating to the latest jar, my Lebowski suite was running perfectly with no failures.

Here is the jar I used:
http://code.google.com/p/selenium/downloads/detail?name=selenium-server-standalone-2.0rc2.jar&can=2&q=

Upgraded selenium-server jar to version 2.0rc2 in order to support Firefox 4

### CODE REVIEW

**Comment by FrozenCanuck** [comment]
Hey, sorry for the looooooong delay getting back to you on this :P. In any case, great that you looked into this and discovered that SC2 can just be swapped in in order to provide support for the latest FF. That being said, I want to avoid having a massive binary file as a commit for this project (It's over 15 MB -- Yikes!). Rather, I'm going to create a setup script that will automatically fetch the latest SC2.

**Comment by luccastera** [comment]
FrozenCanuck,

Thanks for the reply. Yes it's probably wiser to not save that huge file in
the git repo.

Thanks for the help. Are you still using Lebowski?

Luc

On Tue, Jul 19, 2011 at 1:25 PM, FrozenCanuck <
reply@reply.github.com>wrote:

> Hey, sorry for the looooooong delay getting back to you on this :P. In any
> case, great that you looked into this and discovered that SC2 can just be
> swapped in in order to provide support for the latest FF. That being said, I
> want to avoid having a massive binary file as a commit for this project
> (It's over 15 MB -- Yikes!). Rather, I'm going to create a setup script that
> will automatically fetch the latest SC2.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/FrozenCanuck/Lebowski/pull/16#issuecomment-1608884

## 

---

Luc Castera
http://www.intellum.com
Phone: 571-765-1982
Skype: luc.castera

**Comment by FrozenCanuck** [comment]
Yep, still using Lebowski. A lot of updates to the framework have been made but over the last few months they have all remained internal. Getting things ready to that I can finally release all the changes to the public very soon. Just have to go through an internal post-back review process (legal reasons).

**Comment by luccastera** [comment]
That's great to hear. Looking forward to see what will be released.

Best,
Luc

On Thu, Jul 21, 2011 at 2:53 PM, FrozenCanuck <
reply@reply.github.com>wrote:

> Yep, still using Lebowski. A lot of updates to the framework have been made
> but over the last few months they have all remained internal. Getting things
> ready to that I can finally release all the changes to the public very soon.
> Just have to go through an internal post-back review process (legal
> reasons).
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/FrozenCanuck/Lebowski/pull/16#issuecomment-1625952

## 

---

Luc Castera
http://www.intellum.com
Phone: 571-765-1982
Skype: luc.castera

**Pull request closed without merging**
